In [2]:
import numpy as np

In [3]:
# Training data
X = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],  # 0
    [0, 0, 0, 0, 0, 0, 0, 1],  # 1
    [0, 0, 0, 0, 0, 0, 1, 0],  # 2
    [0, 0, 0, 0, 0, 0, 1, 1],  # 3
    [0, 0, 0, 0, 0, 1, 0, 0],  # 4
    [0, 0, 0, 0, 0, 1, 0, 1],  # 5
    [0, 0, 0, 0, 0, 1, 1, 0],  # 6
    [0, 0, 0, 0, 0, 1, 1, 1],  # 7
    [0, 0, 0, 0, 1, 0, 0, 0],  # 8
    [0, 0, 0, 0, 1, 0, 0, 1]   # 9
])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) # Even (0) or odd (1)


In [4]:
class Perceptron:
    def __init__(self, learning_rate = 0.1 , n_iter = 10):
        self.lr = learning_rate
        self.n_iter = n_iter
        
    def Fit(self, X ,y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        
        for i in range(self.n_iter):
            for xi,yi in zip(X,y):
                output = self.predict(xi)
                error = yi - output
                self.weights = self.weights  + self.lr*error*xi
                self.bias = self.bias + self.lr * error
                
                
    def predict(self,X):
        return int(np.dot(X , self.weights) + self.bias >= 0 )
                

In [5]:
p = Perceptron()
p.Fit(X,y)

In [6]:
test_data = np.array([[0,0,1,0,1,1,0,0], # 44 (even)
                      [0,0,1,0,1,1,0,1], # 45 (odd)
                      [1,1,1,1,1,1,1,1]])# 255 (odd)

In [7]:
for xi in test_data:
    prediction = p.predict(xi)
    print(f"{xi} : {prediction}")

[0 0 1 0 1 1 0 0] : 0
[0 0 1 0 1 1 0 1] : 1
[1 1 1 1 1 1 1 1] : 1
