In [4]:
import numpy as np

In [34]:
X1 = np.array([[1, -1, 1, -1]])
X2 = np.array([[-1, -1, 1, 1]])
X3 = np.array([[1, 1, -1, -1]])
X4 = np.array([[1, 1, 1, 1]])



# X1 = np.array([[1, 1, 1, 1, 1, 1]])
# X2 = np.array([[-1, -1, -1, -1, -1, -1]])
# X3 = np.array([[1, -1, -1, 1, 1, 1]])
# X4 = np.array([[1, 1, -1, -1, -1, -1]])

X=[X1, X2, X3, X4]

Y1 = np.array([[1 ,0 ,1]])
Y2 = np.array([[1, 1, 1]])
Y3 = np.array([[0, 1, 1]])
Y4 = np.array([[1, 1, 0]])

# Y1 = np.array([[1, 1, 1]])
# Y2 = np.array([[-1, -1, -1]])
# Y3 = np.array([[-1, 1, 1]])
# Y4 = np.array([[1, -1, 1]])


Y= [Y1, Y2, Y3, Y4]

In [35]:
def calcWeight(X, Y):
    return np.dot(X.T, Y)

In [36]:
def weights(X,Y):
    weis=[]
    for i in range(4):
        weis.append(calcWeight(X[i], Y[i]))
    return weis

In [37]:
weis=weights(X,Y)

In [38]:
def forward_aggregation(X,W):
    result=[]
    for i in range(len(X)):
        result.append(X[i]@W[i])
    return np.squeeze(result)

In [39]:
def activation(X):
    X = np.array(X)
    X[X > 0] = 1
    X[X == 0] = 0
    X[X < 0] = -1
    return X

In [40]:
for_aggri = forward_aggregation(X, weis)

In [41]:
for_aggri

array([[4, 0, 4],
       [4, 4, 4],
       [0, 4, 4],
       [4, 4, 0]])

In [42]:
print(activation(for_aggri))

[[1 0 1]
 [1 1 1]
 [0 1 1]
 [1 1 0]]


In [43]:
def backward_aggregation(X,W):
    result=[]
    for i in range(len(X)):
        result.append(W[i]@X[i].T)
    return np.squeeze(result)

In [44]:
back_aggri = backward_aggregation(Y, weis)

In [45]:
back_aggri

array([[ 2, -2,  2, -2],
       [-3, -3,  3,  3],
       [ 2,  2, -2, -2],
       [ 2,  2,  2,  2]])

In [46]:
print(activation(back_aggri))

[[ 1 -1  1 -1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]
 [ 1  1  1  1]]
